language:
  - php
  - c

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5

compiler:
  - gcc
  - clang

services:
  - mongodb
  - memcached

before_install:
 - ./unit-tests/ci/install_prereqs.sh
 - ./unit-tests/ci/setup_dbs.sh
 - sudo apt-get -qq install valgrind

before_script:
 - git submodule --quiet update --init --recursive
 - (cd php-tests/library/Mustache; git checkout master)
 - (cd php-tests/library/Twig; git checkout master)
 - (cd unit-tests/engines/; git clone -q git://github.com/bobthecow/mustache.php.git & git clone -q git://github.com/fabpot/Twig.git & wait)
 - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -Werror -Wno-error=uninitialized"; phpize && ./configure --silent --enable-phalcon && make --silent -j4 > /dev/null && sudo make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini)
 - ulimit -c unlimited || true

script:
 - (cd ext; NO_INTERACTION=1 make test)
 - USE_ZEND_ALLOC=0 ZEND_DONT_UNLOAD_MODULES=1 valgrind --leak-check=full --read-var-info=yes --track-origins=yes --fullpath-after= $(phpenv which php) ./unit-tests/ci/phpunit.php -c unit-tests/phpunit.xml
 - PHALCON_NO_RVO=1 USE_ZEND_ALLOC=0 ZEND_DONT_UNLOAD_MODULES=1 valgrind --leak-check=full --fullpath-after= $(phpenv which php) ./unit-tests/ci/phpunit.php -c unit-tests/phpunit.xml

after_failure:
 - sudo apt-get -qq install gdb
 - ./unit-tests/ci/after_failure.sh

notifications:
  email:
    - vladimir@free-sevastopol.com
