language:
  - php
  - c

php:
  - 5.5

services:
  - mongodb
  - memcached

env:
  global:
    secure: XX/Nm2O/9m53reDTM5SBp0MkXem6dTZ+LkcDAB+Oe4uoEFhUaenEyc1Fkeic0RIj35gs2NU8p3f3dhv0fC2qSODvVO52TaBP3UUk+4ogyGpN9p8gKjgoBVTZZQDpKGqz1nVVCi5HFmoltNdtVkZtcl1rhaPzRtjqcZ2qd7zjjIk=

before_install:
  - ./unit-tests/ci/install_prereqs.sh
  - ./unit-tests/ci/setup_dbs.sh

before_script:
  - git submodule --quiet update --init --recursive
  - (cd php-tests/library/Mustache; git checkout master)
  - (cd php-tests/library/Twig; git checkout master)
  - (cd unit-tests/engines/; git clone -q git://github.com/bobthecow/mustache.php.git & git clone -q git://github.com/fabpot/Twig.git & wait)
  - (cd ext; export CFLAGS="-g3 -O0 -std=gnu90 -Wall -Werror -Wno-error=uninitialized"; phpize && ./configure --silent --enable-phalcon --enable-coverage && make --silent -j4 > /dev/null && sudo make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - ulimit -c unlimited || true

script:
  - (cd ext; make coverage)

notifications:
  email:
  - vladimir@phalconphp.com

after_success:
  - ./unit-tests/ci/update-gh-pages.sh
